name: JobBridge Scraper

on:
  schedule:
    # Every 30 minutes
    - cron: "*/30 * * * *"

  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Packages
        run: npm install

      - name: Run Scraper
        run: node src/index.js

      - name: Commit Updated jobs.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add jobs.json

          git diff --cached --quiet || git commit -m "Auto update jobs"

          git push